# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         ObjectDBI
version:      0.03
version_from: lib/ObjectDBI.pm
installdirs:  site
requires:
    DBI:                           1.3

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
