--- #YAML:1.0
name:               ObjectDBI
version:            0.14
abstract:           Perl Object Persistence in an RDBMS using DBI
author:
    - Kees Jan Hermans <kees@pink-frog.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    DBI:  1.3
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
