--- #YAML:1.0
name:                ObjectDBI
version:             0.15
abstract:            Perl Object Persistence in an RDBMS using DBI
license:             ~
author:              
    - Kees Jan Hermans <kees@pink-frog.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    DBI:                           1.3
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
